# platform: linux-64
name: adversarial_spatial
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.7
  - tensorflow-gpu=1.15
  - numpy=1.19
  - scipy=1.3
  - tqdm=4.48
  - cudatoolkit=10.0
  - cudnn=7.6
